name: Daily Access Report

on:
  schedule:
    # Executa todo dia às 18h (horário UTC, ajuste conforme necessário)
    - cron: '0 21 * * *'  # 21:00 UTC = 18:00 BRT
  workflow_dispatch:  # Permite execução manual

jobs:
  send-daily-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install pandas pygsheets pytz
      
      - name: Generate and send report
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          ADMIN_EMAILS: ${{ secrets.ADMIN_EMAILS }}
        run: |
          python scripts/send_daily_report.py
